import { dirname, extname, relative } from "node:path";
import type { EngineResult, FileOutcome } from "./types.ts";

const HEADER = `/* Generated by normalize-metrics.
   Line-box overrides for the original files. Does not rewrite the fonts. */`;

export type CssFace = {
  family: string;
  weight: number;
  style: string;
  fontPath: string;
  ascent: number;
  descent: number;
  lineGap: number;
  upm: number;
};

export function metricPercent(units: number, upm: number): string {
  if (!Number.isFinite(upm) || upm <= 0) {
    throw new Error("Font has no units per em.");
  }
  const trimmed = ((Math.abs(units) / upm) * 100).toFixed(4).replace(/\.?0+$/, "");
  return `${trimmed}%`;
}

export function fontSrc(cssFile: string, fontFile: string): string {
  const rel = relative(dirname(cssFile), fontFile).split("\\").join("/");
  if (!rel || rel.startsWith(".")) return rel || ".";
  return `./${rel}`;
}

export function fontFormat(fontFile: string): string | null {
  switch (extname(fontFile).toLowerCase()) {
    case ".woff2":
      return "woff2";
    case ".woff":
      return "woff";
    case ".otf":
      return "opentype";
    case ".ttf":
      return "truetype";
    default:
      return null;
  }
}

function cssString(value: string): string {
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r?\n/g, " ");
  return `"${escaped}"`;
}

function cssStyle(style: string | undefined): string {
  if (style === "italic" || style === "oblique") return style;
  return "normal";
}

function cssWeight(weight: number | undefined): number {
  if (!weight || weight < 1 || weight > 1000) return 400;
  return Math.round(weight);
}

const FORMAT_ORDER = ["woff2", "woff", "truetype", "opentype"];

function faceKey(face: CssFace): string {
  return [
    face.family,
    cssWeight(face.weight),
    cssStyle(face.style),
    face.ascent,
    face.descent,
    face.lineGap,
    face.upm,
  ].join("\0");
}

function srcRank(fontFile: string): number {
  const format = fontFormat(fontFile);
  const index = format ? FORMAT_ORDER.indexOf(format) : -1;
  return index === -1 ? FORMAT_ORDER.length : index;
}

export function groupFaces(faces: CssFace[]): CssFace[][] {
  const groups: CssFace[][] = [];
  const indexByKey = new Map<string, number>();
  for (const face of faces) {
    const key = faceKey(face);
    const existing = indexByKey.get(key);
    if (existing == null) {
      indexByKey.set(key, groups.length);
      groups.push([face]);
      continue;
    }
    groups[existing].push(face);
  }
  return groups.map((group) => [...group].sort((a, b) => srcRank(a.fontPath) - srcRank(b.fontPath)));
}

function srcList(faces: CssFace[], cssFile: string): string {
  return faces
    .map((face) => {
      const url = `url(${cssString(fontSrc(cssFile, face.fontPath))})`;
      const format = fontFormat(face.fontPath);
      return format ? `${url} format(${cssString(format)})` : url;
    })
    .join(",\n       ");
}

export function formatFontFace(faces: CssFace[], cssFile: string): string {
  const face = faces[0];
  if (!face) throw new Error("No font faces to write.");
  return [
    "@font-face {",
    `  font-family: ${cssString(face.family)};`,
    `  src: ${srcList(faces, cssFile)};`,
    `  font-weight: ${cssWeight(face.weight)};`,
    `  font-style: ${cssStyle(face.style)};`,
    `  ascent-override: ${metricPercent(face.ascent, face.upm)};`,
    `  descent-override: ${metricPercent(face.descent, face.upm)};`,
    `  line-gap-override: ${metricPercent(face.lineGap, face.upm)};`,
    "}",
  ].join("\n");
}

export function formatStylesheet(faces: CssFace[], cssFile: string): string {
  const blocks = groupFaces(faces).map((group) => formatFontFace(group, cssFile));
  return `${HEADER}\n\n${blocks.join("\n\n")}\n`;
}

export function cssFaces(
  files: Array<{ abs: string; name: string }>,
  outcomes: FileOutcome[],
): CssFace[] {
  const faces: CssFace[] = [];
  files.forEach((file, index) => {
    const outcome = outcomes[index];
    if (!outcome || outcome.status !== "css") return;
    const after = outcome.result.after;
    if (!after) return;
    faces.push(faceFromResult(file, outcome.result));
  });
  return faces;
}

function faceFromResult(file: { abs: string; name: string }, result: EngineResult): CssFace {
  const after = result.after;
  if (!after) {
    throw new Error(`No metrics for ${file.name}`);
  }
  return {
    family: result.family?.trim() || file.name,
    weight: result.weight ?? 400,
    style: result.style ?? "normal",
    fontPath: file.abs,
    ascent: after.ascent,
    descent: after.descent,
    lineGap: after.lineGap,
    upm: after.upm,
  };
}
